# Generated by Django 4.2.1 on 2023-06-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_archive_resource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archive",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="resource",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="resource",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
